version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: prog/1stPartyLibs/quirrel/quirrel/doc/requirements.txt


sphinx:
  configuration: prog/1stPartyLibs/quirrel/quirrel/doc/source/conf.py

formats:
  - htmlzip
