version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: prog/engine2/_docs/render/requirements.txt

sphinx:
  configuration: prog/engine2/_docs/render/docs/conf.py

formats: all
